package view;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Calendar;  
import java.util.GregorianCalendar;  
public class rent extends javax.swing.JFrame {
    
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public void run() {  
        new Thread() {  
            public void run() {  
                int waktu = 0;  
                while (waktu == 0) {  
                    Calendar kalender = Calendar.getInstance();  

                    int tanggal = kalender.get(Calendar.DATE);
                    int bulan = kalender.get(Calendar.MONTH);
                    String namabulan = "";
                        if (bulan == 0){
                            namabulan = "Jan";
                        } else if (bulan == 1) {
                            namabulan = "Feb";
                        } else if (bulan == 2) {
                            namabulan = "Mar";
                        } else if (bulan == 3) {
                            namabulan = "Apr";
                        } else if (bulan == 4) {
                            namabulan = "May";
                        } else if (bulan == 5) {
                            namabulan = "Jun";
                        } else if (bulan == 6) {
                            namabulan = "Jul";
                        }   else if (bulan == 7) {
                            namabulan = "Aug";
                        } else if (bulan == 8) {
                            namabulan = "Sep";
                        } else if (bulan == 9) {
                            namabulan = "Oct";
                        } else if (bulan == 10) {
                            namabulan = "Nov";
                        } else if (bulan == 11) {
                            namabulan = "Des";
                        }
                    int tahun = kalender.get(Calendar.YEAR);
                    int jam = kalender.get(Calendar.HOUR);  
                    int menit = kalender.get(Calendar.MINUTE);  
                    int detik = kalender.get(Calendar.SECOND);  
                    int am_pm = kalender.get(Calendar.AM_PM);

                    String siang_malam = "";  
                    if (am_pm == 1) {  
                        siang_malam = "PM";  
                    } else {  
                        siang_malam = "AM";  
                    }  
 
                    String format_waktu = tanggal + "/" + namabulan + "/" + tahun + " "+ jam + ":" + menit + ":" + detik + " " + siang_malam;  

                    Time1.setText(format_waktu);  
                }  
            }  
        }.start();//ini wajib  
    }  
    
    public rent() {
        initComponents();
        
        connection DB = new connection();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
        run(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        Time = new javax.swing.JLabel();
        ComboNumber = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Length = new javax.swing.JTextField();
        Type2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        BtnCount = new javax.swing.JButton();
        Type = new javax.swing.JLabel();
        Type1 = new javax.swing.JLabel();
        Trans = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        BtnDatabase = new javax.swing.JButton();
        BtnCount1 = new javax.swing.JButton();
        Time1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnPrint = new javax.swing.JButton();
        NoteTitleName = new javax.swing.JLabel();
        NoteValueName = new javax.swing.JLabel();
        NoteTitleNumber = new javax.swing.JLabel();
        NoteValueNumber = new javax.swing.JLabel();
        NoteTitleType = new javax.swing.JLabel();
        NoteValueType = new javax.swing.JLabel();
        NoteTitlePrice = new javax.swing.JLabel();
        NoteValuePrice = new javax.swing.JLabel();
        NoteTitleLength = new javax.swing.JLabel();
        NoteValueLength = new javax.swing.JLabel();
        NoteTitleDays = new javax.swing.JLabel();
        NoteTitleDate = new javax.swing.JLabel();
        NoteValueDate = new javax.swing.JLabel();
        NoteTitleTotal = new javax.swing.JLabel();
        NoteValueTotal = new javax.swing.JLabel();
        NoteTitleAmount = new javax.swing.JLabel();
        NoteValueAmount = new javax.swing.JLabel();
        NoteTitleChange = new javax.swing.JLabel();
        NoteValueChange = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnPay = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TotalPayment = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JLabel();
        BtnClear = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rent"));

        Title.setFont(new java.awt.Font("STCaiyun", 1, 36)); // NOI18N
        Title.setText("MY CARIN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Name Driver");

        InputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNamaActionPerformed(evt);
            }
        });

        Time.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        ComboNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DK 1021 BM", "DK 2121 KL", "DK 1111 LS", "DK 901 KOL" }));
        ComboNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNumberActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Number Police");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText(" Transportation Type");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Price");

        Price.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText(" Length of Rental");

        Length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthActionPerformed(evt);
            }
        });

        Type2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Type2.setText("Days");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Total Rent ");

        Total.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        BtnCount.setBackground(new java.awt.Color(204, 255, 255));
        BtnCount.setText("COUNT");
        BtnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCountActionPerformed(evt);
            }
        });

        Type.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Type1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Trans.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        Harga.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        BtnDatabase.setBackground(new java.awt.Color(204, 204, 255));
        BtnDatabase.setText("ALL DATA");
        BtnDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDatabaseActionPerformed(evt);
            }
        });

        BtnCount1.setBackground(new java.awt.Color(204, 255, 204));
        BtnCount1.setText("BACK TO HOME");
        BtnCount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCount1ActionPerformed(evt);
            }
        });

        Time1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InputNama)
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(70, 70, 70)
                                                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Trans, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Type1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(Length, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Type2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnCount1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnCount, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnDatabase)
                                        .addGap(5, 5, 5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(Title)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Time)
                    .addComponent(Time1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price)
                    .addComponent(Length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type2)
                    .addComponent(Type)
                    .addComponent(Type1)
                    .addComponent(Trans)
                    .addComponent(Harga))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(BtnCount)
                        .addComponent(BtnDatabase)
                        .addComponent(BtnCount1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Note"));

        BtnPrint.setBackground(new java.awt.Color(153, 255, 204));
        BtnPrint.setText("PRINT AND SAVE");
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });

        NoteTitleName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueType.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitlePrice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValuePrice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleLength.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueLength.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleDays.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleDate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueAmount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        NoteTitleChange.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        NoteValueChange.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnPrint))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NoteTitleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoteValueNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NoteTitleType, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoteValueType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NoteTitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NoteValueName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(NoteTitleLength)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NoteValueLength, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NoteTitleDays, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NoteTitlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NoteValuePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NoteTitleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoteValueDate, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NoteTitleChange, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NoteValueChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NoteTitleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NoteValueAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NoteTitleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NoteValueTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoteTitleName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoteValueName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoteTitleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoteValueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoteTitleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteValueNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoteTitleType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteValueType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoteTitlePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteValuePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NoteTitleLength, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoteValueLength, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteTitleDays, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnPrint)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoteTitleTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteValueTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoteTitleAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteValueAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoteTitleChange, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteValueChange, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment"));

        BtnPay.setBackground(new java.awt.Color(204, 255, 204));
        BtnPay.setText("PAY");
        BtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPayActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Total");

        TotalPayment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Amount");

        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Change");

        Kembalian.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        BtnClear.setBackground(new java.awt.Color(204, 255, 204));
        BtnClear.setText("CLEAR");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Amount)
                    .addComponent(Kembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPay)
                    .addComponent(BtnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    private void LengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LengthActionPerformed

    private void ComboNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNumberActionPerformed
        if(ComboNumber.getSelectedItem().equals("DK 1021 BM")){
            Trans.setText("Xenia");
            int harga1 = 300000;
            Harga.setText("Rp. "+harga1);
        }else if((ComboNumber.getSelectedItem().equals("DK 2121 KL"))){
            Trans.setText("Avanza");
            int harga2 = 250000;
            Harga.setText("Rp. "+harga2);
        }else if((ComboNumber.getSelectedItem().equals("DK 1111 LS"))){
            Trans.setText("Ertiga");
            int harga3 = 350000;
            Harga.setText("Rp. "+harga3);
        }else if((ComboNumber.getSelectedItem().equals("DK 901 KOL"))){
            Trans.setText("Ayla");
            int harga4 = 500000;
            Harga.setText("Rp. "+harga4);
        }
    }//GEN-LAST:event_ComboNumberActionPerformed

    private void InputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNamaActionPerformed

    private void BtnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCountActionPerformed
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        if (InputNama.getText().isEmpty() || Length.getText().isEmpty() || Harga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Maaf , Form yang Diisi Kurang Lengkap !!");
        }
        else {
            String harga = Harga.getText();
            Number kursharga = null;
                try {
                    kursharga = kursIndonesia.parse(harga);
                } catch (ParseException ex) {
                    Logger.getLogger(rent.class.getName()).log(Level.SEVERE, null, ex);
                }
            double doubleharga = kursharga.doubleValue();
            String defharga; 
            defharga = String.format("%.2f",doubleharga);
            String lama_sewa = Length.getText();
        
            try {
                int a = Integer.parseInt(lama_sewa); 
                double b = Double.parseDouble(defharga);

                double hasil = b * a;

                Total.setText(kursIndonesia.format(hasil));
                
                int defhasil = (int) hasil;
                String total = String.valueOf(defhasil);
                TotalPayment.setText("Rp. "+total);
            }catch(NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Maaf , Form yang Diisi Tidak Sesuai !!");
            } 
        }
    }//GEN-LAST:event_BtnCountActionPerformed

    private void BtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPayActionPerformed
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        if (Amount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Maaf , Form yang Diisi Kurang Lengkap !!");
        } else {
            String totalbayar = TotalPayment.getText();
            Number kurstotal = null;
                try {
                    kurstotal = kursIndonesia.parse(totalbayar);
                } catch (ParseException ex) {
                    Logger.getLogger(rent.class.getName()).log(Level.SEVERE, null, ex);
                }
            double doubletotal = kurstotal.doubleValue();
            String deftotal; 
            deftotal = String.format("%.2f",doubletotal);
            String bayar = Amount.getText();
            
            try {
                double a = Double.parseDouble(deftotal);
                int b = Integer.parseInt(bayar);

                double kembalian = b - a;
                
                if(kembalian < 0){
                    JOptionPane.showMessageDialog(null, "Maaf , Uang Anda Kurang !!");
                }else{
                    Kembalian.setText(kursIndonesia.format(kembalian));
                    
                    String nama = InputNama.getText();
                    String tanggal = Time1.getText();
                    String number = String.valueOf(ComboNumber.getSelectedItem());
                    String type = Trans.getText();
                    String price = Harga.getText();
                    String length = Length.getText();
                    String total = Total.getText();
                    String bayar1 = Amount.getText();
                    double defbayar = Double.parseDouble(bayar1);
                    String kembalian1 = Kembalian.getText();
                    
                    NoteTitleName.setText("Name Driver");
                    NoteValueName.setText(nama);
                    NoteTitleDate.setText("Date Transaction");
                    NoteValueDate.setText(tanggal);
                    NoteTitleNumber.setText("Number Police");
                    NoteValueNumber.setText(number);
                    NoteTitleType.setText("Type");
                    NoteValueType.setText(type);
                    NoteTitlePrice.setText("Price");
                    NoteValuePrice.setText(price);
                    NoteTitleLength.setText("Length of Rental");
                    NoteValueLength.setText(length);
                    NoteTitleDays.setText("Days");
                    NoteTitleTotal.setText("Total Rent");
                    NoteValueTotal.setText(total);
                    NoteTitleAmount.setText("Amount");
                    NoteValueAmount.setText(kursIndonesia.format(defbayar));
                    NoteTitleChange.setText("Change");
                    NoteValueChange.setText(kembalian1);
                    
                }
            }catch(NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Maaf , Form yang Diisi Tidak Sesuai !!");
            }
        }
    }//GEN-LAST:event_BtnPayActionPerformed
    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        String nama = InputNama.getText();
        
        if (InputNama.getText().isEmpty() || Length.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Maaf , Form yang Diisi Kurang Lengkap atau Belum Anda Proses !!");
        } else if (Amount.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Maaf , Bayar Terlebih Dahulu !!");
        } else {
            try {
                BufferedWriter simpan = new BufferedWriter (new FileWriter(nama + ".txt"));
                String hasil =  "--------------------------- DATA RENTAL MOBIL MY CARIN ---------------------------\n"+
                                "DATE TRANSACTION               : \t"+NoteValueDate.getText()+"\n"+
                                "NAME                           : \t"+InputNama.getText()+"\n"+
                                "NUMBER POLICE                  : \t"+NoteValueNumber.getText()+"\n"+
                                "TYPE                           : \t"+NoteValueType.getText()+"\n"+
                                "PRICE                          : \t"+NoteValuePrice.getText()+"\n"+
                                "LENGTH                         : \t"+NoteValueLength.getText()+" Days\n"+
                                "TOTAL                          : \t"+NoteValueTotal.getText()+"\n"+
                                "PAYMENT                        : \t"+NoteValueAmount.getText()+"\n"+
                                "CHANGE                         : \t"+NoteValueChange.getText();
                simpan.write(hasil);
                simpan.close();
                
                String sql = "INSERT INTO tb_order VALUES ('"+InputNama.getText()+"','"+NoteValueDate.getText()+"','"+NoteValueNumber.getText()+"','"+NoteValueType.getText()+"','"+NoteValuePrice.getText()+"','"+NoteValueLength.getText()+"','"+NoteValueTotal.getText()+"','"+NoteValueAmount.getText()+"','"+NoteValueChange.getText()+"','Dipinjam')";
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                
                InputNama.setText(null);
                Trans.setText(null);
                Harga.setText(null);
                Length.setText(null);
                Total.setText(null);
                TotalPayment.setText(null);
                Amount.setText(null);
                Kembalian.setText(null);
                NoteTitleName.setText(null);
                NoteValueName.setText(null);
                NoteTitleDate.setText(null);
                NoteValueDate.setText(null);
                NoteTitleNumber.setText(null);
                NoteValueNumber.setText(null);
                NoteTitleType.setText(null);
                NoteValueType.setText(null);
                NoteTitlePrice.setText(null);
                NoteValuePrice.setText(null);
                NoteTitleLength.setText(null);
                NoteValueLength.setText(null);
                NoteTitleDays.setText(null);
                NoteTitleTotal.setText(null);
                NoteValueTotal.setText(null);
                NoteTitleAmount.setText(null);
                NoteValueAmount.setText(null);
                NoteTitleChange.setText(null);
                NoteValueChange.setText(null);
                
                JOptionPane.showMessageDialog(null,"Data Berhasil Dicetak dan Disimpan");
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null ,e);
            }
        }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDatabaseActionPerformed
        this.setVisible(false);
        new data().setVisible(true);
    }//GEN-LAST:event_BtnDatabaseActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        InputNama.setText(null);
        Trans.setText(null);
        Harga.setText(null);
        Length.setText(null);
        Total.setText(null);
        TotalPayment.setText(null);
        Amount.setText(null);
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnCount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCount1ActionPerformed
        this.setVisible(false);
        new index().setVisible(true);
    }//GEN-LAST:event_BtnCount1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnCount;
    private javax.swing.JButton BtnCount1;
    private javax.swing.JButton BtnDatabase;
    private javax.swing.JButton BtnPay;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JComboBox<String> ComboNumber;
    private javax.swing.JLabel Harga;
    private javax.swing.JTextField InputNama;
    private javax.swing.JLabel Kembalian;
    private javax.swing.JTextField Length;
    private javax.swing.JLabel NoteTitleAmount;
    private javax.swing.JLabel NoteTitleChange;
    private javax.swing.JLabel NoteTitleDate;
    private javax.swing.JLabel NoteTitleDays;
    private javax.swing.JLabel NoteTitleLength;
    private javax.swing.JLabel NoteTitleName;
    private javax.swing.JLabel NoteTitleNumber;
    private javax.swing.JLabel NoteTitlePrice;
    private javax.swing.JLabel NoteTitleTotal;
    private javax.swing.JLabel NoteTitleType;
    private javax.swing.JLabel NoteValueAmount;
    private javax.swing.JLabel NoteValueChange;
    private javax.swing.JLabel NoteValueDate;
    private javax.swing.JLabel NoteValueLength;
    private javax.swing.JLabel NoteValueName;
    private javax.swing.JLabel NoteValueNumber;
    private javax.swing.JLabel NoteValuePrice;
    private javax.swing.JLabel NoteValueTotal;
    private javax.swing.JLabel NoteValueType;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Time1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalPayment;
    private javax.swing.JLabel Trans;
    private javax.swing.JLabel Type;
    private javax.swing.JLabel Type1;
    private javax.swing.JLabel Type2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
